name: Auto Bump

on:
  schedule:
    # Run every hour.
    - cron: "0 * * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  bump-packages:
    if: github.event.repository.fork == false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Merge PRs
        if: github.event_name == 'pull_request' && github.triggering_actor == 'actionstokenprovider[bot]' # Run this after bump package PRs are created.
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh pr merge ${{ github.event.number }} --auto --rebase
      - name: Set up Homebrew Tap
        run: |
          brew update-reset "$(brew --repository)"
          TAP_BASE=$(brew --taps)/${{ github.repository_owner }}
          mkdir -p $TAP_BASE
          ln -s $GITHUB_WORKSPACE $TAP_BASE/${{ github.event.repository.name }}
      - name: Bump packages
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ steps.app-token.outputs.token }}
          REPO: ${{ github.repository }}
        run: |
          brew bump --no-fork --open-pr --casks --tap=$REPO
          brew bump --no-fork --open-pr --formulae --tap=$REPO
