name: Auto Bump

on:
  schedule:
    # Run every hour.
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  bump-packages:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Ensure the commit could be pushed to the correct branch.
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Update README and commit changes
        if: github.event_name == 'push' # Run this step after bump package PRs are merged.
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          python3 update_readme.py
          pipx install mdformat
          pipx inject mdformat mdformat-gfm
          mdformat README.md

          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Update README to reflect current packages"
          git push "https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git" HEAD:main
      - uses: Homebrew/actions/setup-homebrew@main
      - name: Enum packages
        id: enum-packages
        run: |
          formulae=$(find Formula -name "*.rb" -exec basename {} .rb \; | xargs echo)
          casks=$(find Casks -name "*.rb" -exec basename {} .rb \; | xargs echo)
          echo "formulae: $formulae"
          echo "casks: $casks"
          echo "formulae=$formulae" >> $GITHUB_OUTPUT
          echo "casks=$casks" >> $GITHUB_OUTPUT
      - uses: Homebrew/actions/bump-packages@main
        with:
          fork: false
          token: ${{ steps.app-token.outputs.token }}
          formulae: ${{ steps.enum-packages.outputs.formulae }}
          casks: ${{ steps.enum-packages.outputs.casks }}
      - name: Merge PRs
        if: github.event_name == 'pull_request' && github.actor == 'app/actionstokenprovider' # Run this after bump package PRs are created.
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh pr merge ${{ github.event.number }} --auto --squash
